---
- hosts: webservers
  ansible_become: yes
  ansible_become_method: su
  ansible_become_user: root
  ansible_become_pass: {{root_password}}
  tasks:

  - name: remove Apache2
    zypper:
      name: "apache2"
      state: absent

  - name: install Apache2
    zypper:
      name: "apache2"
      state: present